stages:
  - build
    
build-docker-image:
  stage: build
  services: 
    - docker:dind
  image: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f ./docker/Dockerfile -t $IMAGE .
    - docker push $IMAGE
  variables:
    IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH:$APP_TAG