stages:
  - build

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.fhnw.ch".insteadOf "https://gitlab.fhnw.ch"
  - git submodule sync
  - git submodule update --init

build-docker-image:
  stage: build
  services: 
    - docker:dind
  image: docker
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f ./docker/Dockerfile -t $CI_REGISTRY_IMAGE:base --target base --pull .
    - docker build -f ./docker/Dockerfile -t $CI_REGISTRY_IMAGE:builder --target builder --pull .
    - docker build -f ./docker/Dockerfile -t $IMAGE .
    - docker push $IMAGE
    - docker push $CI_REGISTRY_IMAGE:base
    - docker push $CI_REGISTRY_IMAGE:builder
  variables:
    IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
