IMU_publisher:
    ros__parameters:
        serial_port: "/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_268d41826a56ee1184a833cfde9da576-if00-port0"
        baud_rate: 115200
        frame_id: "base_link"
        imu_topic: "/imu"


