%YAML:1.0 # need to specify the file type at the top!

vicon:
  enabled: true
  max_n: 1
  noise_o: 0.01
  noise_p: 0.01
  do_calib_dt: true
  do_calib_ext: true
  init_cov_dt: 1e-3
  init_cov_ex_o: 1e-3
  init_cov_ex_p: 1e-3
  chi2_mult: 1

vicon0:
  topic: /odomimu
  timeoffset: 0.0
  T_imu_vicon:
    - [0.0,-1.0, 0.0, 1.0]
    - [1.0, 0.0, 0.0, 1.0]
    - [0.0, 0.0, 1.0, 1.0]
    - [0.0, 0.0, 0.0, 1.0]
  topic: "/odom"
  with_cov: false