%YAML:1.0 # need to specify the file type at the top!

wheel:
  enabled: false
  type: "Rover" #  Wheel2DAng, Wheel2DLin, Wheel2DCen, Wheel3DAng, Wheel3DLin, Wheel3DCen
  do_calib_dt: false
  do_calib_ext: false
  do_calib_int: false
  noise_w: .01
  noise_v: .01
  noise_p: .01
  init_cov_dt: 1e-5
  init_cov_ex_o: 1e-4
  init_cov_ex_p: 1e-4
  init_cov_in_b: 1e-4
  init_cov_in_r: 1e-4
  chi2_mult: 15
    # wheel radius, length, width
  intrinsics: [0.143, 0.84, 0.84]
  reuse_of_information: false
  timeoffset:  0.06
  T_imu_wheel:
    - [ 0.998,-0.015, 0.060, 0.140]
    - [ 0.013, 0.999, 0.029, 0.007]
    - [-0.061,-0.028, 0.998,-0.795]
    - [ 0.000, 0.000, 0.000, 1.000]
  topic: "/wheel/joint_states"