%YAML:1.0 # need to specify the file type at the top!

lidar:
  enabled: false
  max_n: 1
  do_calib_dt: false
  do_calib_ext: false
  init_cov_dt: 1e-4
  init_cov_ex_o: 1e-6
  init_cov_ex_p: 1e-6
  max_range: 30.0
  min_range: 1
  chi2_mult: 1
  raw_do_downsample: true
  raw_downsample_size: 2.0
  raw_noise: 0.1
  raw_remove_motion_blur: false # required to set v_angles and h_angles correctly
  raw_point_dt: 1e-6
  map_do_downsample: true
  map_downsample_size: 0.5
  map_noise: 0.1
  map_ngbr_num: 5
  map_ngbr_max_d: 10.0
  map_decay_time: 30 # sec
  map_decay_dist: 30 # m
  map_use_icp: false
  map_icp_dist: 30 # m
  plane_max_p2pd: 0.1
  plane_max_condi: 200.0

lidar0:
  timeoffset: -0.0
  T_imu_lidar:
    - [-1.000, 0.001, 0.020, 0.020]
    - [-0.020,-0.004,-1.000,-0.111]
    - [-0.001,-1.000, 0.004, 0.038]
    - [ 0.000, 0.000, 0.000, 1.000]
  topic: "/qb2/point_cloud"
