transforms:
  # Using RPY (roll, pitch, yaw)
  - frame: "mars_yard"
    parent_frame: "global"
    translation: {x: -12.0, y: 3.0, z: -376.5}
    rotation:
      roll: 0.0
      pitch: 0.0
      yaw: 1.20  # 90 degrees
  - frame: "simple"
    parent_frame: "global"
    translation: {x: 0.0, y: 0.0, z: -1.5}
    rotation:
      roll: 0.0
      pitch: 0.0
      yaw: 0.0  # 0 degrees

resources:
  - path: "http://192.168.31.225:8081/converted/my.obj"
    topic: "/visualization/mars_yard"
    frame: "mars_yard"
    use_materials: true
    namespace: "terrain"
