%YAML:1.0 # need to specify the file type at the top!

tlio:
  enabled: false
  topic: /odomimu
  do_calib_dt: false
  do_calib_ext: false
  do_calib_int: false
  timeoffset: 1.0
  chi2_mult: 1.0
  noise_o: 0.1
  noise_p: 0.1
  init_cov_dt: 0.1
  init_cov_ex_o: 0.1
  init_cov_ex_p: 0.1