%YAML:1.0 # need to specify the file type at the top!

config_system: "config_system.yaml"
config_estimator: "config_estimator.yaml"
config_camera: "config_camera.yaml"
config_imu: "config_imu.yaml"
config_init: "config_init.yaml"
